# This is a basic workflow to help you get started with Actions

name: Add to dev-env-config repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: 'current-repo'

      # Runs a single command using the runners shell
      - name: Get the dev environment config repo
        run: |
          mkdir ../dev-env-config
          gh repo clone sampsn/dev-env-config ../dev-env-config
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Moves all files inside current repo to the dev-env-config
      - name: Move current repo files into dev-env-config
        run: cp -r current-repo/* ../dev-env-config/nvim

      - name: Add user to git config
        run: |
          git config --global user.email "g@samp.sn"
          git config --global user.name "Gabriel Sampson"

      # Adds, commits, and pushes changes to dev-env-config repo
      - name: Adds, commits, and pushes changes to dev-env-config repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ../dev-env-config
          git add -A
          git commit -m "Update nvim config"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/sampsn/dev-env-config.git
          git push origin main
